/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/bust.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import { Material } from "three";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  // Rotate the model a bit to show off the 3D
  const newRef = useRef();

  // const [colorMap, displacementMap, normalMap, roughnessMap, aoMap] =
  //   useTexture([
  //     "/textures/whitemarble_3_basecolor-4K_png.png",
  //     "/textures/whitemarble_3_height-4K.png",
  //     "/textures/whitemarble_3_normal-4K.png",
  //     "/textures/whitemarble_3_roughness-4K.png",
  //     "/textures/whitemarble_3_ambientocclusion-4K.png",
  //   ]);

  useFrame(() => {
    newRef.current.rotation.y += 0.001;
  });

  const { nodes, materials } = useGLTF("/new_hair.gltf");
  return (
    <group {...props} dispose={null} ref={newRef} rotateX={[0, 1, 0]}>
      <mesh
        geometry={nodes["head-mesh"].geometry}
        //material={materials["Light Marble"]}
        position={[0.025, 0.706, 0.515]}
        scale={[4, 4, 4]}
        rotation={[0.3, 0.5, 0]}
        castShadow
      >
        <meshPhysicalMaterial
          attach="material"
          flatShading
          clearcoat={1}
          specularIntensity={0.5}
          castShadow
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/bust.gltf");
