/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/triple_split.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/triple_split.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Far.geometry} material={materials['Light Marble.006']} position={[0.025, 0.706, 0.515]} />
    </group>
  )
}

useGLTF.preload('/triple_split.glb')
